insert into genres (id, name, super_genre, super_id) values (1,  'curabitur at',              'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (2,  'accumsan felis',            'History',   2);
insert into genres (id, name, super_genre, super_id) values (3,  'diam nam tristique',        'Drama',     3);
insert into genres (id, name, super_genre, super_id) values (4,  'lobortis',                  'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (5,  'quam',                      'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (6,  'sapien',                    'History',   2);
insert into genres (id, name, super_genre, super_id) values (7,  'non mi',                    'History',   2);
insert into genres (id, name, super_genre, super_id) values (8,  'duis bibendum',             'Drama',     3);
insert into genres (id, name, super_genre, super_id) values (9,  'est risus',                 'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (10, 'dapibus nulla suscipit',    'Fantastic', 4);
insert into genres (id, name, super_genre, super_id) values (11, 'morbi a',                   'History',   2);
insert into genres (id, name, super_genre, super_id) values (12, 'diam in',                   'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (13, 'tellus nulla',              'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (14, 'duis',                      'History',   2);
insert into genres (id, name, super_genre, super_id) values (15, 'lacus',                     'History',   2);
insert into genres (id, name, super_genre, super_id) values (16, 'non interdum',              'History',   2);
insert into genres (id, name, super_genre, super_id) values (17, 'lacinia nisi venenatis',    'Drama',     3);
insert into genres (id, name, super_genre, super_id) values (18, 'habitasse platea',          'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (19, 'duis',                      'Drama',     3);
insert into genres (id, name, super_genre, super_id) values (20, 'et',                        'History',   2);
insert into genres (id, name, super_genre, super_id) values (21, 'vitae',                     'Fantastic', 4);
insert into genres (id, name, super_genre, super_id) values (22, 'in est risus',              'Drama',     3);
insert into genres (id, name, super_genre, super_id) values (23, 'praesent id',               'Fantastic', 4);
insert into genres (id, name, super_genre, super_id) values (24, 'magna bibendum',            'History',   2);
insert into genres (id, name, super_genre, super_id) values (25, 'elit ac',                   'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (26, 'id massa id',               'Drama',     3);
insert into genres (id, name, super_genre, super_id) values (27, 'ultrices aliquet maecenas', 'Drama',     3);
insert into genres (id, name, super_genre, super_id) values (28, 'dictumst',                  'Drama',     3);
insert into genres (id, name, super_genre, super_id) values (29, 'nibh',                      'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (30, 'porttitor',                 'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (31, 'nulla neque',               'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (32, 'at velit eu',               'Fantastic', 4);
insert into genres (id, name, super_genre, super_id) values (33, 'posuere cubilia curae',     'History',   2);
insert into genres (id, name, super_genre, super_id) values (34, 'proin interdum',            'History',   2);
insert into genres (id, name, super_genre, super_id) values (35, 'nec euismod scelerisque',   'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (36, 'augue',                     'Drama',     3);
insert into genres (id, name, super_genre, super_id) values (37, 'nisi at nibh',              'Drama',     3);
insert into genres (id, name, super_genre, super_id) values (38, 'in',                        'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (39, 'vestibulum sit',            'History',   2);
insert into genres (id, name, super_genre, super_id) values (40, 'eros',                      'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (41, 'vestibulum velit id',       'Fantastic', 4);
insert into genres (id, name, super_genre, super_id) values (42, 'habitasse platea dictumst', 'Drama',     3);
insert into genres (id, name, super_genre, super_id) values (43, 'felis',                     'Fantastic', 4);
insert into genres (id, name, super_genre, super_id) values (44, 'at nibh',                   'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (45, 'iaculis',                   'Drama',     3);
insert into genres (id, name, super_genre, super_id) values (46, 'felis',                     'Fantastic', 4);
insert into genres (id, name, super_genre, super_id) values (47, 'risus praesent',            'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (48, 'in sagittis',               'Drama',     3);
insert into genres (id, name, super_genre, super_id) values (49, 'morbi',                     'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (50, 'vivamus vel',               'History',   2);
insert into genres (id, name, super_genre, super_id) values (51, 'enim sit',                  'Fantastic', 4);
insert into genres (id, name, super_genre, super_id) values (52, 'congue etiam justo',        'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (53, 'nulla nisl',                'History',   2);
insert into genres (id, name, super_genre, super_id) values (54, 'aliquet',                   'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (55, 'quisque porta volutpat',    'Drama',     3);
insert into genres (id, name, super_genre, super_id) values (56, 'donec posuere',             'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (57, 'risus',                     'History',   2);
insert into genres (id, name, super_genre, super_id) values (58, 'vel nulla',                 'History',   2);
insert into genres (id, name, super_genre, super_id) values (59, 'amet turpis elementum',     'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (60, 'pulvinar nulla',            'Fantastic', 4);
insert into genres (id, name, super_genre, super_id) values (61, 'ac',                        'Fantastic', 4);
insert into genres (id, name, super_genre, super_id) values (62, 'primis',                    'Fantastic', 4);
insert into genres (id, name, super_genre, super_id) values (63, 'nisl aenean lectus',        'Drama',     3);
insert into genres (id, name, super_genre, super_id) values (64, 'et',                        'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (65, 'odio',                      'Fantastic', 4);
insert into genres (id, name, super_genre, super_id) values (66, 'ac',                        'Fantastic', 4);
insert into genres (id, name, super_genre, super_id) values (67, 'nullam porttitor',          'Drama',     3);
insert into genres (id, name, super_genre, super_id) values (68, 'ipsum ac',                  'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (69, 'dui',                       'Fantastic', 4);
insert into genres (id, name, super_genre, super_id) values (70, 'posuere cubilia',           'History',   2);
insert into genres (id, name, super_genre, super_id) values (71, 'nec nisi',                  'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (72, 'sit',                       'Fantastic', 4);
insert into genres (id, name, super_genre, super_id) values (73, 'vestibulum',                'History',   2);
insert into genres (id, name, super_genre, super_id) values (74, 'lobortis convallis tortor', 'Drama',     3);
insert into genres (id, name, super_genre, super_id) values (75, 'eget congue',               'Drama',     3);
insert into genres (id, name, super_genre, super_id) values (76, 'curae mauris',              'Drama',     3);
insert into genres (id, name, super_genre, super_id) values (77, 'erat vestibulum sed',       'Fantastic', 4);
insert into genres (id, name, super_genre, super_id) values (78, 'amet cursus id',            'History',   2);
insert into genres (id, name, super_genre, super_id) values (79, 'dapibus',                   'Fantastic', 4);
insert into genres (id, name, super_genre, super_id) values (80, 'volutpat in congue',        'Drama',     3);
insert into genres (id, name, super_genre, super_id) values (81, 'nisi',                      'History',   2);
insert into genres (id, name, super_genre, super_id) values (82, 'sapien cum',                'Fantastic', 4);
insert into genres (id, name, super_genre, super_id) values (83, 'suscipit nulla elit',       'Fantastic', 4);
insert into genres (id, name, super_genre, super_id) values (84, 'mauris non',                'History',   2);
insert into genres (id, name, super_genre, super_id) values (85, 'nascetur ridiculus mus',    'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (86, 'sociis natoque penatibus',  'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (87, 'sem mauris',                'History',   2);
insert into genres (id, name, super_genre, super_id) values (88, 'lacus morbi sem',           'Drama',     3);
insert into genres (id, name, super_genre, super_id) values (89, 'blandit',                   'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (90, 'risus praesent',            'Drama',     3);
insert into genres (id, name, super_genre, super_id) values (91, 'pellentesque eget',         'History',   2);
insert into genres (id, name, super_genre, super_id) values (92, 'curae donec pharetra',      'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (93, 'mattis',                    'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (94, 'praesent blandit',          'Fantastic', 4);
insert into genres (id, name, super_genre, super_id) values (95, 'est',                       'Drama',     3);
insert into genres (id, name, super_genre, super_id) values (96, 'posuere cubilia',           'Fantastic', 4);
insert into genres (id, name, super_genre, super_id) values (97, 'eget orci vehicula',        'Detective', 1);
insert into genres (id, name, super_genre, super_id) values (98, 'sapien dignissim vetibulm', 'Fantastic', 4);
insert into genres (id, name, super_genre, super_id) values (99, 'nullam molestie nibh',      'Fantastic', 4);
insert into genres (id, name, super_genre, super_id) values (100, 'nisi',                     'Fantastic', 4);
