--liquibase formatted sql
--changeset somebody:fill-table-genres runInTransaction:true failOnError:true
insert into genres (id, name, parent_id) values (1,  'Detective', null);
insert into genres (id, name, parent_id) values (2,  'History',   null);
insert into genres (id, name, parent_id) values (3,  'Drama',     null);
insert into genres (id, name, parent_id) values (4,  'Fantastic', null);
insert into genres (id, name, parent_id) values (5,  'curabitur at',              1);
insert into genres (id, name, parent_id) values (6,  'accumsan felis',            2);
insert into genres (id, name, parent_id) values (7,  'diam nam tristique',        3);
insert into genres (id, name, parent_id) values (8,  'lobortis',                  1);
insert into genres (id, name, parent_id) values (9,  'quam',                      1);
insert into genres (id, name, parent_id) values (10, 'sapien',                    2);
insert into genres (id, name, parent_id) values (11, 'non mi',                    2);
insert into genres (id, name, parent_id) values (12, 'duis bibendum',             3);
insert into genres (id, name, parent_id) values (13, 'est risus',                 1);
insert into genres (id, name, parent_id) values (14, 'dapibus nulla suscipit',    4);
insert into genres (id, name, parent_id) values (15, 'morbi a',                   2);
insert into genres (id, name, parent_id) values (16, 'diam in',                   1);
insert into genres (id, name, parent_id) values (17, 'tellus nulla',              1);
insert into genres (id, name, parent_id) values (18, 'duis',                      2);
insert into genres (id, name, parent_id) values (19, 'lacus',                     2);
insert into genres (id, name, parent_id) values (20, 'non interdum',              2);
insert into genres (id, name, parent_id) values (21, 'lacinia nisi venenatis',    3);
insert into genres (id, name, parent_id) values (22, 'habitasse platea',          1);
insert into genres (id, name, parent_id) values (23, 'duis',                      3);
insert into genres (id, name, parent_id) values (24, 'et',                        2);
insert into genres (id, name, parent_id) values (25, 'vitae',                     4);
insert into genres (id, name, parent_id) values (26, 'in est risus',              3);
insert into genres (id, name, parent_id) values (27, 'praesent id',               4);
insert into genres (id, name, parent_id) values (28, 'magna bibendum',            2);
insert into genres (id, name, parent_id) values (29, 'elit ac',                   1);
insert into genres (id, name, parent_id) values (30, 'id massa id',               3);
insert into genres (id, name, parent_id) values (31, 'ultrices aliquet maecenas', 3);
insert into genres (id, name, parent_id) values (32, 'dictumst',                  3);
insert into genres (id, name, parent_id) values (33, 'nibh',                      1);
insert into genres (id, name, parent_id) values (34, 'porttitor',                 1);
insert into genres (id, name, parent_id) values (35, 'nulla neque',               1);
insert into genres (id, name, parent_id) values (36, 'at velit eu',               4);
insert into genres (id, name, parent_id) values (37, 'posuere cubilia curae',     2);
insert into genres (id, name, parent_id) values (38, 'proin interdum',            2);
insert into genres (id, name, parent_id) values (39, 'nec euismod scelerisque',   1);
insert into genres (id, name, parent_id) values (40, 'augue',                     3);
insert into genres (id, name, parent_id) values (41, 'nisi at nibh',              3);
insert into genres (id, name, parent_id) values (42, 'in',                        1);
insert into genres (id, name, parent_id) values (43, 'vestibulum sit',            2);
insert into genres (id, name, parent_id) values (44, 'eros',                      1);
insert into genres (id, name, parent_id) values (45, 'vestibulum velit id',       4);
insert into genres (id, name, parent_id) values (46, 'habitasse platea dictumst', 3);
insert into genres (id, name, parent_id) values (47, 'felis',                     4);
insert into genres (id, name, parent_id) values (48, 'at nibh',                   1);
insert into genres (id, name, parent_id) values (49, 'iaculis',                   3);
insert into genres (id, name, parent_id) values (50, 'felis',                     4);
insert into genres (id, name, parent_id) values (51, 'risus praesent',            1);
insert into genres (id, name, parent_id) values (52, 'in sagittis',               3);
insert into genres (id, name, parent_id) values (53, 'morbi',                     1);
insert into genres (id, name, parent_id) values (54, 'vivamus vel',               2);
insert into genres (id, name, parent_id) values (55, 'enim sit',                  4);
insert into genres (id, name, parent_id) values (56, 'congue etiam justo',        1);
insert into genres (id, name, parent_id) values (57, 'nulla nisl',                2);
insert into genres (id, name, parent_id) values (58, 'aliquet',                   1);
insert into genres (id, name, parent_id) values (59, 'quisque porta volutpat',    3);
insert into genres (id, name, parent_id) values (60, 'donec posuere',             1);
insert into genres (id, name, parent_id) values (61, 'risus',                     2);
insert into genres (id, name, parent_id) values (62, 'vel nulla',                 2);
insert into genres (id, name, parent_id) values (63, 'amet turpis elementum',     1);
insert into genres (id, name, parent_id) values (64, 'pulvinar nulla',            4);
insert into genres (id, name, parent_id) values (65, 'ac',                        4);
insert into genres (id, name, parent_id) values (66, 'primis',                    4);
insert into genres (id, name, parent_id) values (67, 'nisl aenean lectus',        3);
insert into genres (id, name, parent_id) values (68, 'et',                        1);
insert into genres (id, name, parent_id) values (69, 'odio',                      4);
insert into genres (id, name, parent_id) values (70, 'ac',                        4);
insert into genres (id, name, parent_id) values (71, 'nullam porttitor',          3);
insert into genres (id, name, parent_id) values (72, 'ipsum ac',                  1);
insert into genres (id, name, parent_id) values (73, 'dui',                       4);
insert into genres (id, name, parent_id) values (74, 'posuere cubilia',           2);
insert into genres (id, name, parent_id) values (75, 'nec nisi',                  1);
insert into genres (id, name, parent_id) values (76, 'sit',                       4);
insert into genres (id, name, parent_id) values (77, 'vestibulum',                2);
insert into genres (id, name, parent_id) values (78, 'lobortis convallis tortor', 3);
insert into genres (id, name, parent_id) values (79, 'eget congue',               3);
insert into genres (id, name, parent_id) values (80, 'curae mauris',              3);
insert into genres (id, name, parent_id) values (81, 'erat vestibulum sed',       4);
insert into genres (id, name, parent_id) values (82, 'amet cursus id',            2);
insert into genres (id, name, parent_id) values (83, 'dapibus',                   4);
insert into genres (id, name, parent_id) values (84, 'volutpat in congue',        3);
insert into genres (id, name, parent_id) values (85, 'nisi',                      2);
insert into genres (id, name, parent_id) values (86, 'sapien cum',                4);
insert into genres (id, name, parent_id) values (87, 'suscipit nulla elit',       4);
insert into genres (id, name, parent_id) values (88, 'mauris non',                2);
insert into genres (id, name, parent_id) values (89, 'nascetur ridiculus mus',    1);
insert into genres (id, name, parent_id) values (90, 'sociis natoque penatibus',  1);
insert into genres (id, name, parent_id) values (91, 'sem mauris',                2);
insert into genres (id, name, parent_id) values (92, 'lacus morbi sem',           3);
insert into genres (id, name, parent_id) values (93, 'blandit',                   1);
insert into genres (id, name, parent_id) values (94, 'risus praesent',            3);
insert into genres (id, name, parent_id) values (95, 'pellentesque eget',         2);
insert into genres (id, name, parent_id) values (96, 'curae donec pharetra',      1);
insert into genres (id, name, parent_id) values (97, 'mattis',                    1);
insert into genres (id, name, parent_id) values (98, 'praesent blandit',          4);
insert into genres (id, name, parent_id) values (99, 'est',                       3);
insert into genres (id, name, parent_id) values (100,'posuere cubilia',           4);
insert into genres (id, name, parent_id) values (101,'eget orci vehicula',        1);
insert into genres (id, name, parent_id) values (102,'sapien dignissim vetibulm', 4);
insert into genres (id, name, parent_id) values (103,'nullam molestie nibh',      4);
insert into genres (id, name, parent_id) values (104,'nisi',                      4);
--rollback rollback;